### ISSUE TITLE
Add All Local Currencies 

### ISSUE THREAD

**Issue by malawi8333** [MostroP2P/mostro-web#48]
It's very important to have all local currencies, and not only the major ones.

**Comment by bilthon** [comment]
The set of fiat currencies shown in the web interface is dependent on the ones used by the mostro backend. Which in turn relies on the [Yadio API](https://github.com/MostroP2P/mostro/issues). So this issue is better filed [here](https://github.com/MostroP2P/mostro/issues).

 But before you do that, let me ask you what fiat currency specifically are you looking for? and is there a reliable API for it?

**Comment by malawi8333** [comment]
Yadio has just added Malawian currency (MWK)

Thank you[Screenshot_20240824-202959.png]
